### ISSUE TITLE
task checklist: display

### ISSUE THREAD

**Issue by louking** [louking/members#17]
- [x] show latest completion status
- [x] change color of completion status depending on status - https://datatables.net/reference/option/columns.createdCell
- [ ] ~~show fields entered (?)~~ see #22
